server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 256MB
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fwwb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

conda:
  python:
    path: "./src/main/resources/env/fwwb_yolo/python.exe"

logging:
  level:
    org.springframework: DEBUG
    org.springframework.beans: TRACE
    org.springframework.context.annotation: TRACE
    com.fwwb.vehicledetection: DEBUG  # 添加你的项目包路径日志级别