server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 256MB
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fwwb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

conda:
  python:
    path: "./src/main/resources/env/fwwb_yolo/python.exe"

logging:
  level:
    root: INFO           # 全局日志级别（DEBUG, INFO, WARN, ERROR）
    org.springframework: WARN  # 单独设置Spring框架日志级别
    com.example: DEBUG   # 设置特定包的日志级别
