server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fwwb
    username: 13168
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "your-256-bit-secret-key-here"
    expiration: 86400000