server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/fwwb
    username: 13168
    password: 1234
    driver-class-name: org.postgresql.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    io:
#      lettuce=DEBUG:

yolo:
  model:
    path: "/runs/model"
  output:
    dir: "/runs/result"

