server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 256MB
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fwwb
    username: 13168
    password: 1234
    driver-class-name: org.postgresql.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

conda:
  python:
    path: "D:/Work/Tools/Anaconda/envs/yolov5/python.exe"


